### ISSUE TITLE
What is the point of this project? 

### ISSUE THREAD

**Issue by meifpga** [design-gateway/aes256-xts-stg-4x#1]
What is the point of this project? It's a waste of emotions. Absolutely nothing, it's worse than trashy advertising

**Comment by design-gateway** [comment]
Thank you for your interesting and question.
This project is a simple demo to demonstrate our IP Core Product on any your own FPGA boards.
You may request for free evaluation license of our IP Core, please contact us dgway.com/contact.html.
https://youtu.be/FEoKKayIkJI
